### ISSUE TITLE
PyPI version mismatch

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-backend#102]
As of today, oonibackend latest version is [1.3.1](https://github.com/TheTorProject/ooni-backend/releases/tag/v1.3.1) whereas the latest PyPI version is [1.1.4](https://pypi.python.org/pypi/oonibackend).

**Comment by hellais** [comment]
Is anybody using ooni-backend via pypi?

I have stopped publishing ooni-backend on pypi since a long time ago and should probably delete it from there as it's clearly not up to date.

**Comment by anadahz** [comment]
If the pypi version of ooni-backend isn't we should remove it from the pypi.
We should then change any deployment scripts that use the pypi version of oonibackend.

**Comment by hellais** [comment]
Yeah, that's why I was asking if anybody or anything was using it? I suggest we remove it from pypi as it's not a package that we distribute.

**Comment by hellais** [comment]
I have unpublished all of the oonibackend versions on pypi: https://pypi.python.org/pypi/oonibackend. Closing.
