### ISSUE TITLE
Huge amounts of messages from twisted

### ISSUE THREAD

**Issue by andresazp** [TheTorProject/ooni-backend#59]
On one of the servers we have a ooni backend running we find an incredibly high number messages from Twisted (many per second) constantly

Messages like:
Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x1c7fa10>
DNSDatagramProtocol starting on 49989
Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x1c7f990>
(UDP Port 49989 Closed)
Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x1c7f990>
DNSDatagramProtocol starting on 13088
Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x1c7fdd0>
(UDP Port 13088 Closed)
Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x1c7fdd0>
Unhandled Error
Traceback (most recent call last):
Failure: twisted.names.error.DNSQueryTimeoutError: 

Unhandled Error
Traceback (most recent call last):
Failure: twisted.names.error.DNSQueryTimeoutError: 

Unhandled Error
Traceback (most recent call last):
Failure: twisted.names.error.DNSQueryTimeoutError: 

Unhandled Error
Traceback (most recent call last):
Failure: twisted.names.error.DNSQueryTimeoutError:

**Comment by anadahz** [comment]
Could you please send debug/error log?
Which twisted version are you running?
Which version of ooni-backend are you running?

**Comment by hellais** [comment]
Is this still an issue?

Can we close this?

**Comment by andresazp** [comment]
I think is over, but let me confirm this checking the new collector (in a  few days, currently traveling)On Dec 5, 2016, at 12:11 PM, Arturo Filastò <notifications@github.com> wrote:Is this still an issue?Can we close this?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TheTorProject/ooni-backend","title":"TheTorProject/ooni-backend","subtitle":"GitHub repository","main_image_url":"<a href="<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a></a>","avatar_image_url":"<a href="<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a></a>","action":{"name":"Open in GitHub","url":"<a href="<a href="https://github.com/TheTorProject/ooni-backend" class="">https://github.com/TheTorProject/ooni-backend</a>" class=""><a href="https://github.com/TheTorProject/ooni-backend" class="">https://github.com/TheTorProject/ooni-backend</a></a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hellais in #59: Is this still an issue?\r\n\r\nCan we close this?"}],"action":{"name":"View Issue","url":"<a href="<a href="https://github.com/TheTorProject/ooni-backend/issues/59#issuecomment-264930407" class="">https://github.com/TheTorProject/ooni-backend/issues/59#issuecomment-264930407</a>" class=""><a href="https://github.com/TheTorProject/ooni-backend/issues/59#issuecomment-264930407" class="">https://github.com/TheTorProject/ooni-backend/issues/59#issuecomment-264930407</a></a>"}}}

**Comment by hellais** [comment]
I am going to close this issue. If this is still a problem please report back here and re-open it! Thanks!
