### ISSUE TITLE
Tor not started when privileges are dropped

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooni-backend#65]
I was testing #62 and #64 under Vagrant precise32 with a custom configuration file where user and group ids pointed to nobody's user id. This is the diff with respect to the default config file:

```diff
--- oonib.conf.example	2016-03-14 19:49:34.000000000 +0100
+++ oonib.conf	2016-03-14 23:18:58.000000000 +0100
@@ -19,9 +19,9 @@
     chroot: null
     rundir: .
     umask: null
-    euid: null
-    uid: null
-    gid: null
+    euid: 65534
+    uid: 65534
+    gid: 65534
     uuid: null
     no_save: true
     profile: null
```

What I noticed is that with this configuration file tor never actually went up and hidden services were not exposed.

**Comment by anadahz** [comment]
@bassosimone possibly related: https://trac.torproject.org/projects/tor/ticket/13116

**Comment by bassosimone** [comment]
Yes, I think so! Thank you @anadahz!
