### ISSUE TITLE
New HS endpoint code doesn't respect tor_datadir

### ISSUE THREAD

**Issue by joelanders** [TheTorProject/ooni-backend#73]
I introduced an embarrassing regression in PR #69 where the `torconfig` isn't passed to the endpoint-starting code. It's now taking the default config from txtorcon and using a temporary datadir.

**Comment by joelanders** [comment]
https://github.com/meejah/txtorcon/blob/master/txtorcon/endpoints.py#L215
`TCPHiddenServiceEndpoint.global_tor()` doesn't take a `tor_datadir` argument.

Maybe we should take the advice (a few lines down in the above link)?:
```
It's probably best to not specify any option besides
`public_port`, `hidden_service_dir`, and maybe `local_port`
unless you have a specific need to.
```

Do we have a specific need for
* socks_port (we're never using it here)
* control_port (we can let txtorcon choose this)
* tor2web mode
* tor_datadir (txtorcon generates a safe tempdir, do we ever need to persist the contents?)

(We could get rid of all of `oonib/onion.py` if we don't need these things)

**Comment by hellais** [comment]
I think this can be closed now.
